version: "2"

linters:
  default: none
  enable:
    - govet
  settings:
    govet:
      disable:
        - inline

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/abahmed/kwatch
