apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
    {{- if gt (int .Values.replicaCount) 1 }}
    leaderElection:
      enabled: true
    {{- end }}