apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kwatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kwatch.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 }}
  selector:
    matchLabels:
      {{- include "kwatch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kwatch.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      serviceAccountName:  {{ .Release.Name }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: /config
          env:
            - name: CONFIG_FILE
              value: "/config/config.yaml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}
