{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kwatch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kwatch.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "kwatch.selectorLabels" . | nindent 6 }}
{{- end }}
