package config

func DefaultConfig() *Config {
	return &Config{
		App:                          App{LogFormatter: "text"},
		IgnoreFailedGracefulShutdown: true,
		ReportStartupBaseline:        true,
		MaxRecentLogLines:            50,
		ResyncSeconds:                0,
		Workers:                      1,
		PvcMonitor:                   PvcMonitor{Enabled: true, Interval: 5, Threshold: 80, CriticalThreshold: 90, ClearThreshold: 75},
		NodeMonitor:                  NodeMonitor{Enabled: true, SustainedMinutes: 3},
		ScheduleMonitor:              ScheduleMonitor{Enabled: true},
		OomMonitor:                   OomMonitor{Enabled: true, Threshold: 3, WindowMinutes: 60},
		PendingPodMonitor:            PendingPodMonitor{Enabled: true, Threshold: 300},
		NotReadyMonitor:              NotReadyMonitor{Enabled: true},
		RolloutMonitor:               RolloutMonitor{Enabled: true, SustainedMinutes: 2},
		JobMonitor:                   JobMonitor{Enabled: true},
		CronJobMonitor:               CronJobMonitor{Enabled: true, SustainedMinutes: 5},
		StatefulSetMonitor:           StatefulSetMonitor{Enabled: true, SustainedMinutes: 5},
		PdbMonitor:                   PdbMonitor{Enabled: true, SustainedMinutes: 5},
		NodeResourceMonitor:          NodeResourceMonitor{Enabled: true, IntervalSeconds: 300, CpuWarning: 2.0, CpuCritical: 4.0, MemWarning: 2.0, MemCritical: 4.0},
		DaemonSetMonitor:             DaemonSetMonitor{Enabled: true, SustainedMinutes: 5},
		HpaMonitor:                   HpaMonitor{Enabled: true, SustainedMinutes: 20},
		ClusterAutoscalerMonitor:     ClusterAutoscalerMonitor{Enabled: true},
		Upgrader:                     Upgrader{DisableUpdateCheck: false},
		HealthCheck:                  HealthCheck{Enabled: true, Port: 8060, Pprof: false, Diagnostics: false},
		Inhibition:                   Inhibition{NodeSuppressesPods: true},
		LLM:                          LLMConfig{Enabled: false},
		ServiceMonitor:               ServiceMonitor{Enabled: true},
		AdmissionWebhookMonitor:      AdmissionWebhookMonitor{Enabled: true},
		ControlPlaneMonitor:          ControlPlaneMonitor{Enabled: true},
		IngressMonitor:               IngressMonitor{Enabled: true},
		NetworkPolicyMonitor:         NetworkPolicyMonitor{Enabled: true},
		SmartGrouping:                SmartGrouping{WindowSeconds: 60},
		Correlation: Correlation{
			MaxBaseline:       5000,
			Window:            10,
			LifecycleInterval: 1,
			ResolveHoldDown:   300,
			CooldownMinutes:   10,
			Escalation:        EscalationConfig{Enabled: true, Tiers: []int{3, 10, 50}},
		},
		AuditLog: AuditLogConfig{Enabled: true, Output: "stdout"},
	}
}
